sudo: required
services:
  - docker
language: python
python:
  - "2.7"
env:
  matrix:
    - IMAGE=centos7
    - IMAGE=jessie
install:
  - pip install testinfra
script:
  - python run-tests.py test $IMAGE -v
